import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Banner from "./components/Banner";
import { Nav } from "./components/Nav";
import Footer from "./components/Footer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <div className="h-[200px] relative">
          <Image
            src="/knollsestate.jpg"
            fill={true}
            alt="knolls estate"
            style={{ objectFit: "cover" }}
            quality={100}
            sizes="100vw"
          />
        </div>
        <Banner />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
